In [15]:
import pandas as pd

In [17]:
df = pd.read_csv("MASTER_system_and_weather.csv")

In [19]:
df.tail(30)

,Date,Generated (kWh),Efficiency,System Name,Location,System Size (kW),Solar_Irradiance,Temperature_2m,Cloud_Cover
3932,3/26/2025,225.893,2.091602,Nugali,Brazil,108.000,11.73,22.8,92
3933,3/26/2025,1399.132,3.334204,MAWC,Maldives,419.630,23.32,28.1,42
3934,3/27/2025,135.810,1.479412,HLT1 Klagenfurt Lastenstrasse,Austria,91.800,13.41,9.3,90
3935,3/27/2025,104.243,2.084860,Wray Farms,United Kingdom,50.000,13.06,9.6,58
3936,3/27/2025,1150.000,2.280050,Pentaari,Greece,504.375,11.11,10.2,96
3937,3/27/2025,1427.867,5.649996,Wannon Water,Australia,252.720,19.31,16.9,25
3938,3/27/2025,410.776,3.803481,Nugali,Brazil,108.000,17.91,23.8,77
3939,3/27/2025,103.293,1.589123,Feuerwehr,Switzerland,65.000,9.12,7.8,92
3940,3/27/2025,1727.360,3.465672,Schipper Power- Three,Netherlands,498.420,17.12,7.4,34
3941,3/27/2025,1866.433,3.680601,siris-D-500kW,Greece,507.100,12.62,13.2,95
3942,3/27/2025,743.860,6.612089,DeCrescent 178kW PV,United States,112.500,19.75,27.1,90
3943,3/27/2025,1898.824,4.524996,MAWC,Maldives,419.630,24.21,28.2,79
3944,3/28/2025,62.267,0.678290,HLT1 Klagenfurt Lastenstrasse,Austria,91.800,5.97,8.1,98
3945,3/28/2025,100.611,1.547862,Feuerwehr,Switzerland,65.000,14.12,6.7,61
3946,3/28/2025,1125.239,4.452513,Wannon Water,Australia,252.720,17.85,17.0,68
3947,3/28/2025,427.154,3.796924,DeCrescent 178kW PV,United States,112.500,17.97,25.3,96
3948,3/28/2025,2651.000,5.256010,Pentaari,Greece,504.375,18.22,9.4,78
3949,3/28/2025,1775.921,3.502112,siris-D-500kW,Greece,507.100,15.59,12.3,62
3950,3/28/2025,634.879,1.512950,MAWC,Maldives,419.630,26.19,29.2,30
3951,3/28/2025,91.659,1.833180,Wray Farms,United Kingdom,50.000,14.13,9.8,54
3952,3/28/2025,867.820,1.741142,Schipper Power- Three,Netherlands,498.420,12.47,8.3,47
3953,3/28/2025,417.938,3.869796,Nugali,Brazil,108.000,17.42,24.8,91
3954,3/29/2025,622.247,2.462199,Wannon Water,Australia,252.720,11.30,16.9,61
3955,3/29/2025,598.146,1.179542,siris-D-500kW,Greece,507.100,14.71,10.9,79
3956,3/29/2025,1415.110,2.839192,Schipper Power- Three,Netherlands,498.420,15.88,8.3,61
3957,3/29/2025,78.258,1.203969,Feuerwehr,Switzerland,65.000,7.67,8.2,99
3958,3/29/2025,978.000,1.939033,Pentaari,Greece,504.375,6.41,7.7,98
3959,3/29/2025,1947.200,4.640278,MAWC,Maldives,419.630,24.62,29.3,29
3960,3/29/2025,106.771,2.135420,Wray Farms,United Kingdom,50.000,15.80,8.1,59
3961,3/29/2025,60.475,0.658769,HLT1 Klagenfurt Lastenstrasse,Austria,91.800,3.03,7.8,100

In [53]:
df.columns

Index(['Date', 'Generated (kWh)', 'Efficiency', 'System Name', 'Location',
       'System Size (kW)', 'Solar_Irradiance', 'Temperature_2m',
       'Cloud_Cover'],
      dtype='object')

In [21]:
columns_to_normalize = ['Generated (kWh)','System Size (kW)', 'Solar_Irradiance', 'Temperature_2m',
       'Cloud_Cover', 'Efficiency']

In [23]:
for col in columns_to_normalize: 
    max_value = df[col].max()
    print(f"{df[col].name}: {max_value}")
    if (max_value != 0):
        df[col] = df[col] / max_value
    else:
        df[col] = 0

Generated (kWh): 3506.128
System Size (kW): 507.1
Solar_Irradiance: 33.16
Temperature_2m: 31.5
Cloud_Cover: 100
Efficiency: 7.929972222

In [59]:
df.tail(30)

,Date,Generated (kWh),Efficiency,System Name,Location,System Size (kW),Solar_Irradiance,Temperature_2m,Cloud_Cover
3932,3/26/2025,0.064428,0.263759,Nugali,Brazil,0.212976,0.353739,0.723810,0.92
3933,3/26/2025,0.399053,0.420456,MAWC,Maldives,0.827509,0.703257,0.892063,0.42
3934,3/27/2025,0.038735,0.186560,HLT1 Klagenfurt Lastenstrasse,Austria,0.181029,0.404403,0.295238,0.90
3935,3/27/2025,0.029732,0.262909,Wray Farms,United Kingdom,0.098600,0.393848,0.304762,0.58
3936,3/27/2025,0.327997,0.287523,Pentaari,Greece,0.994626,0.335042,0.323810,0.96
3937,3/27/2025,0.407249,0.712486,Wannon Water,Australia,0.498363,0.582328,0.536508,0.25
3938,3/27/2025,0.117159,0.479634,Nugali,Brazil,0.212976,0.540109,0.755556,0.77
3939,3/27/2025,0.029461,0.200395,Feuerwehr,Switzerland,0.128180,0.275030,0.247619,0.92
3940,3/27/2025,0.492669,0.437035,Schipper Power- Three,Netherlands,0.982883,0.516285,0.234921,0.34
3941,3/27/2025,0.532335,0.464138,siris-D-500kW,Greece,1.000000,0.380579,0.419048,0.95
3942,3/27/2025,0.212160,0.833810,DeCrescent 178kW PV,United States,0.221850,0.595597,0.860317,0.90
3943,3/27/2025,0.541573,0.570619,MAWC,Maldives,0.827509,0.730097,0.895238,0.79
3944,3/28/2025,0.017759,0.085535,HLT1 Klagenfurt Lastenstrasse,Austria,0.181029,0.180036,0.257143,0.98
3945,3/28/2025,0.028696,0.195191,Feuerwehr,Switzerland,0.128180,0.425814,0.212698,0.61
3946,3/28/2025,0.320935,0.561479,Wannon Water,Australia,0.498363,0.538299,0.539683,0.68
3947,3/28/2025,0.121831,0.478807,DeCrescent 178kW PV,United States,0.221850,0.541918,0.803175,0.96
3948,3/28/2025,0.756105,0.662803,Pentaari,Greece,0.994626,0.549457,0.298413,0.78
3949,3/28/2025,0.506519,0.441630,siris-D-500kW,Greece,1.000000,0.470145,0.390476,0.62
3950,3/28/2025,0.181077,0.190789,MAWC,Maldives,0.827509,0.789807,0.926984,0.30
3951,3/28/2025,0.026143,0.231171,Wray Farms,United Kingdom,0.098600,0.426116,0.311111,0.54
3952,3/28/2025,0.247515,0.219565,Schipper Power- Three,Netherlands,0.982883,0.376055,0.263492,0.47
3953,3/28/2025,0.119202,0.487996,Nugali,Brazil,0.212976,0.525332,0.787302,0.91
3954,3/29/2025,0.177474,0.310493,Wannon Water,Australia,0.498363,0.340772,0.536508,0.61
3955,3/29/2025,0.170600,0.148745,siris-D-500kW,Greece,1.000000,0.443607,0.346032,0.79
3956,3/29/2025,0.403610,0.358033,Schipper Power- Three,Netherlands,0.982883,0.478890,0.263492,0.61
3957,3/29/2025,0.022320,0.151825,Feuerwehr,Switzerland,0.128180,0.231303,0.260317,0.99
3958,3/29/2025,0.278940,0.244520,Pentaari,Greece,0.994626,0.193305,0.244444,0.98
3959,3/29/2025,0.555370,0.585157,MAWC,Maldives,0.827509,0.742461,0.930159,0.29
3960,3/29/2025,0.030453,0.269285,Wray Farms,United Kingdom,0.098600,0.476478,0.257143,0.59
3961,3/29/2025,0.017248,0.083073,HLT1 Klagenfurt Lastenstrasse,Austria,0.181029,0.091375,0.247619,1.00

In [63]:
df.to_csv("NORMALIZED_MASTER.csv", index=False)